# docker-compose.yaml
version: '3.8'

services:
    frontend:
        container_name: about-intrinsic
        build:
            context: .
            args:
              - VITE_AI_SERVER_HOST=http://localhost:8080
        ports:
            - 3000:80
