name: Deploy Azure Resources and Web Application to Environment

on:
  workflow_call:
    inputs:
      environmentType:
        type: string
      resourceGroupName:
        type: string
      DOCKER_BASE_URL:
        type: string
      DOCKER_IMAGE_NAME_AND_TAG:
        type: string
    secrets:
      DOCKER_USERNAME:
        required: true
      DOCKER_PASSWORD:
        required: true
      AZURE_CREDENTIALS:
        required: true

jobs:
  deploy-infra:
    environment:
      name: 'production'
    runs-on: ubuntu-latest
    outputs:
      webAppName: ${{ steps.deploy-infrastructure.outputs.webAppName }}
    steps:
    - uses: actions/checkout@v3
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - uses: azure/arm-deploy@v1
      id: deploy-infrastructure
      with:
        resourceGroupName: ${{ inputs.resourceGroupName }}
        template: ./deploy/main.bicep
        parameters: environmentType=${{ inputs.environmentType }} dockerImageFullUrl=${{ inputs.DOCKER_BASE_URL }}/${{ secrets.DOCKER_USERNAME }}/${{ inputs.DOCKER_IMAGE_NAME_AND_TAG }}

  build:
    runs-on: 'ubuntu-latest'
    needs: deploy-infra

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: ${{ inputs.DOCKER_BASE_URL }}/${{ secrets.DOCKER_USERNAME }}/${{ inputs.DOCKER_IMAGE_NAME_AND_TAG }}
        file: ./Dockerfile
        build-args: VITE_AI_SERVER_HOST=https://ai-prod-webapp.azurewebsites.net

  deploy-app:
    runs-on: ubuntu-latest
    needs: [deploy-infra, build]
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - uses: azure/login@v1
      name: Sign in to Azure
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ needs.deploy-infra.outputs.webAppName }}
        images: '${{ inputs.DOCKER_BASE_URL }}/${{ secrets.DOCKER_USERNAME }}/${{ inputs.DOCKER_IMAGE_NAME_AND_TAG }}'
    - name: Set Docker Settings in Web App
      uses: azure/cli@v2
      with: 
        inlineScript: |
          az webapp config container set \
            --docker-registry-server-url 'https://${{ inputs.DOCKER_BASE_URL }}' \
            --name ${{ needs.deploy-infra.outputs.webAppName }} \
            --resource-group ${{ inputs.resourceGroupName }}