name: Deploy Azure Resources and Web Application to all Environments

on:
  push:
    branches:
    - master
    - features/docker-hub-for-images
  workflow_dispatch:

env:
  AZURE_RESOURCEGROUP_NAME: intrinsic-rg
  ENVIRONMENT: nonprod

permissions:
  id-token: write
  contents: read

jobs:
  test:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
            node-version: '20'
      - name: 'Install node packages'
        run: npm i
      - name: 'Run tests'
        run: npm run test
    outputs:
      resourceGroupName: ${{ env.AZURE_RESOURCEGROUP_NAME }}

  # deploy-to-nonprod:
  #   needs: test
  #   uses: './.github/workflows/deploy-infra-and-website-to-env.yml'
  #   with:
  #     environmentType: 'nonprod'
  #     resourceGroupName: ${{ needs.test.outputs.resourceGroupName }}
  #   secrets:
  #     AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
  #     AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
  #     AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  #     AzureAppService_ContainerUsername: ${{ secrets.AzureAppService_ContainerUsername_b39ad9b085d94d62a5cac8feedfcc353 }}
  #     AzureAppService_ContainerPassword: ${{ secrets.AzureAppService_ContainerPassword_5968fbbf25fa492887c20302677761ef }}

  deploy-to-prod:
    needs: [test]
    uses: './.github/workflows/deploy-infra-and-website-to-env.yml'
    with:
      environmentType: 'prod'
      resourceGroupName: ${{ needs.test.outputs.resourceGroupName }}
      DOCKER_BASE_URL: index.docker.io
      DOCKER_IMAGE_NAME_AND_TAG: about-intrinsic:latest
    secrets:
      AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
