name: Deploy Azure Resources and Web Application

on:
  workflow_dispatch:

env:
  AZURE_RESOURCEGROUP_NAME: intrinsic-rg
  ENVIRONMENT: nonprod

jobs:
  test:
    runs-on: 'ubuntu-latest'
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: '20'
    - name: 'Install node packages'
      run: npm i
    - name: 'Run tests'
      run: npm run test

  deploy-to-nonprod:
    needs: test
    uses: './.github/workflows/deploy-infra-and-website-to-env.yml'
    with:
      environmentType: 'nonprod'
      resourceGroupName: ${{ env.AZURE_RESOURCEGROUP_NAME }}

  deploy-to-prod:
    needs: deploy-tp-nonprod
    uses: './.github/workflows/deploy-infra-and-website-to-env.yml'
    with:
      environmentType: 'prod'
      resourceGroupName: ${{ env.AZURE_RESOURCEGROUP_NAME }}