name: Build and deploy container app to Azure Web App - intrinsic-michal-turczyn

on:
  # push:
  #   branches:
  #     - master
  #     - features/docker-hub-for-images
  workflow_dispatch:

env:
  DOCKER_BASE_URL: index.docker.io
  DOCKER_IMAGE_NAME_AND_TAG: about-intrinsic:latest

jobs:
  test:
    runs-on: 'ubuntu-latest'
    
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: '20'
    - name: 'Install node packages'
      run: npm i
    - name: 'Run tests'
      run: npm run test
  
  deploy-infrastructure:
    needs: [test]
    runs-on: ubuntu-latest
    outputs:
      webAppName: ${{ steps.deploy-infrastructure-step.outputs.webAppName }}
    steps:
    - uses: actions/checkout@v3
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - uses: azure/arm-deploy@v1
      id: deploy-infrastructure-step
      with:
        resourceGroupName: intrinsic-rg
        template: ./deploy/main.bicep
        parameters: dockerImageFullUrl=${{ env.DOCKER_BASE_URL }}/${{ secrets.DOCKER_USERNAME }}/${{ env.DOCKER_IMAGE_NAME_AND_TAG }}
  
  build:
    needs: [deploy-infrastructure]
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and Push Docker image to Docker Hub
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: ${{ env.DOCKER_BASE_URL }}/${{ secrets.DOCKER_USERNAME }}/${{ env.DOCKER_IMAGE_NAME_AND_TAG }}
        file: ./Dockerfile
        build-args: VITE_AI_SERVER_HOST=https://ai-prod-webapp.azurewebsites.net

    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ needs.deploy-infrastructure.outputs.webAppName }}
        images: '${{ env.DOCKER_BASE_URL }}/${{ secrets.DOCKER_USERNAME }}/${{ env.DOCKER_IMAGE_NAME_AND_TAG }}'
      
    - name: Set Docker Settings in Web App
      uses: azure/cli@v2
      with: 
        inlineScript: |
          az webapp config container set \
            --docker-registry-server-url '${{ env.DOCKER_BASE_URL }}/${{ secrets.DOCKER_USERNAME }}/${{ env.DOCKER_IMAGE_NAME_AND_TAG }}' \
            --name ${{ needs.deploy-infrastructure.outputs.webAppName }} \
            --resource-group intrinsic-rg